"use strict";
exports.PERSONS = [
    { familly: "Hodac", name: 'Anne-Laure' },
    { familly: "Hodac", name: 'Dao' },
    { familly: "Hodac", name: 'Fanny' },
    { familly: "Hodac", name: 'Paula' },
    { familly: "Hodac", name: 'Lucie' },
    { familly: "Brehault", name: 'Barbichu' },
    { familly: "Brehault", name: 'Caro' },
    { familly: "Brehault", name: 'Gabriel' },
    { familly: "Brehault", name: 'Victor' },
    { familly: "Brehault", name: 'Capucine' },
    { familly: "Lebreton", name: 'Etienne' },
    { familly: "Lebreton", name: 'Sophie' },
    { familly: "Lebreton", name: 'Pierre' },
    { familly: "Lebreton", name: 'Guillaume' },
    { familly: "Lebreton", name: 'Antoine' },
    { familly: "Andrieu", name: 'Agnes' },
    { familly: "Andrieu", name: 'Matthieu' },
    { familly: "Andrieu", name: 'Matisse' },
    { familly: "Andrieu", name: 'Simon' },
    { familly: "Andrieu", name: 'Elsa' },
    { familly: "Andrieu", name: 'Greg' },
    { familly: "Andrieu", name: 'Sophie' },
    { familly: "Andrieu", name: 'Zoe' },
    { familly: "Andrieu", name: 'Gabriel' },
    { familly: "Andrieu", name: 'Alice' },
];
//# sourceMappingURL=mock-persons.js.map